### ISSUE TITLE
Pydantic v1 errors

### ISSUE THREAD

**Issue by Jonas1312** [langfuse/langfuse-python#1054]
Hi,

I'm having some pydantic v1 warning in my logs:

```
------------------------------ Captured log call -------------------------------
ERROR    langfuse:client.py:2631 6 validation errors for UpdateGenerationBody
usageDetails -> completion_tokens_details
  value is not a valid integer (type=type_error.integer)
usageDetails -> prompt_tokens_details
  value is not a valid integer (type=type_error.integer)
usageDetails -> prompt_tokens_details -> audio_tokens
  none is not an allowed value (type=type_error.none.not_allowed)
usageDetails -> completion_tokens_details -> accepted_prediction_tokens
  none is not an allowed value (type=type_error.none.not_allowed)
usageDetails -> completion_tokens_details -> audio_tokens
  none is not an allowed value (type=type_error.none.not_allowed)
usageDetails -> completion_tokens_details -> rejected_prediction_tokens
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/Users/jonasm/.venv/lib/python3.11/site-packages/langfuse/client.py", line 2617, in update
    request = UpdateGenerationBody(**generation_body)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonasm/.venv/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 6 validation errors for UpdateGenerationBody
usageDetails -> completion_tokens_details
  value is not a valid integer (type=type_error.integer)
usageDetails -> prompt_tokens_details
  value is not a valid integer (type=type_error.integer)
usageDetails -> prompt_tokens_details -> audio_tokens
  none is not an allowed value (type=type_error.none.not_allowed)
usageDetails -> completion_tokens_details -> accepted_prediction_tokens
  none is not an allowed value (type=type_error.none.not_allowed)
usageDetails -> completion_tokens_details -> audio_tokens
  none is not an allowed value (type=type_error.none.not_allowed)
usageDetails -> completion_tokens_details -> rejected_prediction_tokens
  none is not an allowed value (type=type_error.none.not_allowed)
 ```

Thanks

```
name = "langfuse"
version = "2.57.0"
name = "openai"
version = "1.56.2"
name = "pydantic"
version = "2.10.3"
```

**Comment by urunimi** [comment]
@Jonas1312 I got same error. How did you resolve it?

**Comment by Jonas1312** [comment]
> @Jonas1312 I got same error. How did you resolve it?

not solved yet

https://github.com/langfuse/langfuse/issues/4961
