### ISSUE TITLE
Amazon Bedrock and Authropic Claude issue with indenting model_name

### ISSUE THREAD

**Issue by kobrinartem** [langfuse/langfuse-python#133]
How to set model name so that LangFuse can get it. I have errors:

'model_name'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/langfuse/callback.py", line 479, in __on_llm_action
    model_name = kwargs["invocation_params"]["model_name"]
KeyError: 'model_name'
run not found
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/langfuse/callback.py", line 541, in on_llm_end
    raise Exception("run not found")
Exception: run not found

**Comment by kobrinartem** [comment]
quick fix: https://github.com/langfuse/langfuse-python/pull/134

**Comment by maxdeichmann** [comment]
@kobrinartem thanks for the contribution. PR is merged. Please re-open in case of issues.
